export default function LogoIcon({ size = 48, color = "#C9A84C", className = "" }) {
  return (
    <svg
      width={size}
      height={size * 0.55}
      viewBox="0 0 110 60"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
    >
      <line
        x1="8"
        y1="44"
        x2="8"
        y2="30"
        stroke={color}
        strokeWidth="2.8"
        strokeLinecap="round"
      />
      <line
        x1="46"
        y1="44"
        x2="46"
        y2="30"
        stroke={color}
        strokeWidth="2.8"
        strokeLinecap="round"
      />
      <line
        x1="8"
        y1="44"
        x2="46"
        y2="44"
        stroke={color}
        strokeWidth="2.8"
        strokeLinecap="round"
      />
      <line
        x1="4"
        y1="32"
        x2="27"
        y2="12"
        stroke={color}
        strokeWidth="3"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <line
        x1="27"
        y1="12"
        x2="50"
        y2="32"
        stroke={color}
        strokeWidth="3"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <rect
        x="18"
        y="28"
        width="18"
        height="14"
        rx="1"
        stroke={color}
        strokeWidth="2"
        fill="none"
      />
      <line x1="27" y1="28" x2="27" y2="42" stroke={color} strokeWidth="1.2" />
      <line x1="18" y1="35" x2="36" y2="35" stroke={color} strokeWidth="1.2" />
      <line
        x1="46"
        y1="28"
        x2="106"
        y2="28"
        stroke={color}
        strokeWidth="3"
        strokeLinecap="round"
      />
      <circle cx="50" cy="28" r="7" stroke={color} strokeWidth="2.5" fill="none" />
      <circle cx="50" cy="28" r="2.5" fill={color} />
      <line
        x1="82"
        y1="28"
        x2="82"
        y2="36"
        stroke={color}
        strokeWidth="2.5"
        strokeLinecap="round"
      />
      <line
        x1="92"
        y1="28"
        x2="92"
        y2="34"
        stroke={color}
        strokeWidth="2.5"
        strokeLinecap="round"
      />
      <line
        x1="102"
        y1="28"
        x2="102"
        y2="37"
        stroke={color}
        strokeWidth="2.5"
        strokeLinecap="round"
      />
      <line
        x1="106"
        y1="24"
        x2="106"
        y2="32"
        stroke={color}
        strokeWidth="2.5"
        strokeLinecap="round"
      />
    </svg>
  );
}
